language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

sudo: false

before_script:
  - phpenv config-rm xdebug.ini
  - composer selfupdate
  - composer install --prefer-source --dev

script: vendor/bin/phpunit
